baseURL = "https://kajian-hsi.netlify.app/"
copyright = "© Dibuat Oleh"
disqusShortname = "santekno"
googleAnalytics = "G-BWJTN85WY2"
languageCode = "id-ID"
paginate = 10
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "solarized-dark"
summaryLength = 20
theme = "ezhil"
title = "Catatan Kajian"
[[menu.main]]
name = "Materi Kajian"
url = "/categories"
weight = 2
[[menu.main]]
name = "Tag"
url = "/tags"
weight = 5
[[menu.main]]
name = "Tentang"
url = "/about"
weight = 4
[[menu.main]]
name = "Semua"
url = "/posts"
weight = 3
[[menu.main]]
name = "Beranda"
url = "/"
weight = 1
[params]
customCSS = "css/custom.css"
customDarkCSS = "css/custom-dark.css"
customJS = ["js/abc.js", "js/xyz.js", "https://code.jquery.com/jquery-3.4.1.js"]
disableDisqusTypes = ["page"]
favicon = "icons/myicon.png"
featherIconsCDN = true
mainSections = ["posts"]
mode = "auto"
subtitle = "Halaqah Silsilah Ilmiyyah oleh Ustadz Abdullah Roy [HSI Edu](https://edu.hsi.id)"
[[params.social]]
icon = "github"
name = "Github"
url = "https://github.com/ihsanarifr"
[[params.social]]
icon = "twitter"
name = "Twitter"
url = "https://twitter.com/ihsanarifr"
[taxonomies]
tag = "tags"
